# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Wired In
tagline:          'A modern productivity tool for Mac, iOS & your desk.'
description:      'A modern productivity tool for Mac, iOS & your desk.'
url:              http://blog.wearewired.In

author:
  name:           'Caleb Hicks'
  url:            https://twitter.com/wearewiredin

paginate:         5

# Site Specific
logo:			  /public/images/logo.png
accent:			  498fcc

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/wearewiredin/wired-in-blog
